# Travis CI config for the AppStream Generator
language: d
sudo: required
dist: trusty

services:
  - docker

d:
  - gdc
  #- ldc -- LDC has problems with parallelization (doesn't seem to work on Package[] array)

before_script:
  - docker build -t asgen -f test/ci/Dockerfile .

script:
  - docker run -t -e DC=$DC -v `pwd`:/build asgen
    ./test/ci/build_and_test.sh
